routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * Domain #1 SaddleBrooke Golf
 ---------------------------------------------------------------------------------------------------------------------*/
Route::domain(config('app.domain_1'))->group(function () {
    //SaddleBrooke Golf
    Route::namespace('Sb2Golf')->group(function () {
        Route::get('/', 'HomePageController@index')->name('home');
        //Top navigation
        Route::get('/tee-times/mountainview', 'TeeTimesController@mountainview')->name('tee.times.mountainview');
        Route::get('/tee-times/preserve', 'TeeTimesController@preserve')->name('tee.times.preserve');
        //Footer
        Route::get('/tee-times-mountainview', 'TeeTimesController@mountainview')->name('tee.times.mountainview.footer');
        Route::get('/tee-times-preserve', 'TeeTimesController@preserve')->name('tee.times.preserve.footer');

        Route::get('/golf/mountainview', 'HomePageController@mountainview')->name('golf.mountainview');
        Route::get('/golf/preserve', 'HomePageController@preserve')->name('golf.preserve');
        Route::get('/outings', 'HomePageController@outings')->name('group.outings');
        Route::get('/facilities', 'HomePageController@facilities')->name('sb2facilities');
        Route::get('/rates', 'RatesController@index')->name('sb2rates');
        Route::get('/annuals', 'RatesController@annuals')->name('sb2rates.annuals');
        Route::get('/play-cards', 'RatesController@playCards')->name('sb2rates.play-cards');
        Route::get('/casual-golfer', 'RatesController@casualGolfer')->name('sb2rates.casual-golfer');
        Route::get('/contact', 'ContactController@index')->name('sb2contact.index');
        // Route::get('/', function (){
        //     return view("master.sb2golf.under-construction.index");
        // });
        // Route::get('/', function (){
        //     return redirect('http://sbhoa2.org/golf');
        // });
    });


    // Admin Routs
    Auth::routes(['register' => false, 'verify' => true]);
    Route::namespace('Admin')
        ->prefix('admin')
        ->name('admin.')
        ->middleware('verified')
        ->group(function () {
            // Controllers Within The "App\Http\Controllers\Admin" Namespace
            Route::get('/', function (){
                return redirect()->route('admin.dashboard');
            });
            Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
            Route::get('/events', 'EventsController')->name('events');
    });
});

/**
 * Domain #2 MountainView Golf Club
 ---------------------------------------------------------------------------------------------------------------------*/
Route::domain(config('app.domain_2'))->group(function () {
    //Redirect to Admin Panel
    Route::get('/admin', function (){
        return redirect(config('app.domain_1').'/admin');
    });
    //MountainView Golf
    Route::namespace('MvGolf')->group(function () {
        Route::get('/', 'HomePageController@index')->name('index');
        Route::get('/tee-times', 'TeeTimesController@index')->name('tee.times');

        Route::get('/rates', 'RatesController@index')->name('rates');
        Route::get('/annuals', 'RatesController@annuals')->name('rates.annuals');
        Route::get('/play-cards', 'RatesController@playCards')->name('rates.play-cards');
        Route::get('/casual-golfer', 'RatesController@casualGolfer')->name('rates.casual-golfer');

        Route::get('/facilities', 'HomePageController@facilities')->name('facilities');
        Route::get('/outings', 'HomePageController@outings')->name('outings');
        Route::get('/contact', 'ContactController@index')->name('contact.index');
    });
});

/**
 * Domain #3 The Preserve Golf Club
 ---------------------------------------------------------------------------------------------------------------------*/
Route::domain(config('app.domain_3'))->group(function () {
    //Redirect to Admin Panel
    Route::get('/admin', function (){
        return redirect(config('app.domain_1').'/admin');
    });
    //The Preserve Golf
    Route::namespace('PreserveGolf')
        ->name('preserve.')
        ->group(function () {
            Route::get('/', 'HomePageController@index')->name('index');
            Route::get('/tee-times', 'TeeTimesController@index')->name('tee.times');
            Route::get('/teetimes', 'TeeTimesController@index')->name('teetimes');

            Route::get('/rates', 'RatesController@index')->name('rates');
            Route::get('/annuals', 'RatesController@annuals')->name('rates.annuals');
            Route::get('/play-cards', 'RatesController@playCards')->name('rates.play-cards');
            Route::get('/casual-golfer', 'RatesController@casualGolfer')->name('rates.casual-golfer');

            Route::get('/facilities', 'HomePageController@facilities')->name('facilities');
            Route::get('/outings', 'HomePageController@outings')->name('outings');
            Route::get('/contact', 'ContactController@index')->name('contact.index');
        });
});

app/Http/Controllers/PreserveGolf/BaseController.php
<?php

namespace App\Http\Controllers\PreserveGolf;

use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BaseController extends Controller
{
    protected $template;
    public $clubname;

    public function __construct()
    {
        $this->clubname = 'The Preserve Golf Club';
        $this->template = 'master.preservegolf';
    }

    public function nowDate()
    {
        return Carbon::now();
    }
}

app/Http/Controllers/PreserveGolf/ContactController.php
<?php

namespace App\Http\Controllers\PreserveGolf;

use App\Mail\Preserve\{ContactFormMessage, OutingsInquiry};
use Ctct\{Components\Contacts\Contact, ConstantContact, Exceptions\CtctException};

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class ContactController extends BaseController
{
    const API_KEY = '6guh6t7r7cfhssv6gbxeynmw';
    const ACCESS_TOKEN = 'eb618e20-8681-4678-90bf-11e3d760f16e';
    const MVG_ID = '1869203453';
    const ACTION_BY = 'ACTION_BY_OWNER'; // ACTION_BY_VISITOR

    const TO_MAIL = ['Matt Hudson' => 'matt.hudson@sbhoa2.org'];
    const CC_MAIL = ['Mike Karpe' => 'mike.karpe@sbhoa2.org'];
    const BCC_MAIL = ['Kathy N' => 'kathy@sbhoa2.org'];

    protected $template;

    public function __construct()
    {
        parent::__construct();
        $this->template = "$this->template.contact";
    }
    
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view("$this->template.index");
    }

    public function subscribe(Request $request)
    {
        $request->validate([
            'email' => 'required|email'
        ]);

        $cc = new ConstantContact(self::API_KEY);
        // attempt to fetch lists in the account, catching any exceptions and printing the errors to screen
        try {
            $lists = $cc->listService->getLists(self::ACCESS_TOKEN);
        } catch (CtctException $ex) {
            foreach ($ex->getErrors() as $error) {
                print_r($error);
            }
            if (!isset($lists)) {
                $lists = null;
            }
        }
        // check if the form was submitted
        if (isset($request->email) && strlen($request->email) > 1) {
            $action = "Getting Contact By Email Address";
            try {
                // check to see if a contact with the email address already exists in the account
                $response = $cc->contactService->getContacts(self::ACCESS_TOKEN, ["email" => $request->email]);
                // create a new contact if one does not exist
                if (empty($response->results)) {
                    $action = "Creating Contact";
                    $contact = new Contact();
                    $contact->addEmail($request->email);
                    $contact->addList(self::MVG_ID);
                    $contact->first_name = '';
                    $contact->last_name = '';
                    /*
                     * The third parameter of addContact defaults to false, but if this were set to true it would tell Constant
                     * Contact that this action is being performed by the contact themselves, and gives the ability to
                     * opt contacts back in and trigger Welcome/Change-of-interest emails.
                     *
                     * See: http://developer.constantcontact.com/docs/contacts-api/contacts-index.html#opt_in
                     */
                    $returnContact = $cc->contactService->addContact(self::ACCESS_TOKEN, $contact, ['action_by' => self::ACTION_BY]);
                    // update the existing contact if address already existed
                } else {
                    $action = "Updating Contact";
                    $contact = $response->results[0];
                    if ($contact instanceof Contact) {
                        $contact->addList(self::MVG_ID);
                        $contact->first_name = '';
                        $contact->last_name = '';
                        /*
                         * The third parameter of updateContact defaults to false, but if this were set to true it would tell
                         * Constant Contact that this action is being performed by the contact themselves, and gives the ability to
                         * opt contacts back in and trigger Welcome/Change-of-interest emails.
                         *
                         * See: http://developer.constantcontact.com/docs/contacts-api/contacts-index.html#opt_in
                         */
                        $returnContact = $cc->contactService->updateContact(self::ACCESS_TOKEN, $contact, ['action_by' => self::ACTION_BY]);
                    } else {
                        $e = new CtctException();
                        $e->setErrors(["type", "Contact type not returned"]);
                        throw $e;
                    }
                }

                return $action;
                // catch any exceptions thrown during the process and print the errors to screen
            } catch (CtctException $ex) {
                echo '<span class="label label-important">Error ' . $action . '</span>';
                echo '<div class="container alert-error"><pre class="failure-pre">';
                print_r($ex->getErrors());
                echo '</pre></div>';
                die();
            }
        }
    }

    public function outingsInquiry(Request $request)
    {
        $request->validate([
            'name' => 'required|min:3|max:191',
            'email' => 'required|email',
            'event_details' => 'required|max:500'
        ]);

        Mail::to(self::TO_MAIL)
            ->cc(self::CC_MAIL)
            ->bcc(self::BCC_MAIL)
            ->send(new OutingsInquiry($request));

        $data = 'sent'; //view('master.about.contact.response')->render();
        return response()->json($data, 200, [], JSON_PRETTY_PRINT);
    }

    public function contactForm(Request $request)
    {
        $request->validate([
            'name' => 'required|min:3|max:191',
            'email' => 'required|email',
            'input_comments' => 'required|max:500'
        ]);

        Mail::to(self::TO_MAIL)
            ->cc(self::CC_MAIL)
            ->bcc(self::BCC_MAIL)
            ->send(new ContactFormMessage($request));

        $data = 'sent'; //view('master.about.contact.response')->render();
        return response()->json($data, 200, [], JSON_PRETTY_PRINT);
    }
}

app/Http/Controllers/PreserveGolf/EventController.php
<?php

namespace App\Http\Controllers\PreserveGolf;

use App\Event;
use App\Http\Resources\Event as EventResource;

class EventController extends BaseController
{
    /**
     * @return \Illuminate\Http\Resources\Json\AnonymousResourceCollection
     */
    public function index()
    {
        $events = Event::with('picture')
            ->where('expired_at', '>', $this->nowDate())
            ->orderByDesc('created_at')
            ->paginate(3);

        return EventResource::collection($events);
    }
}

app/Http/Controllers/PreserveGolf/HomePageController.php
<?php

namespace App\Http\Controllers\PreserveGolf;

use Illuminate\Http\Request;

class HomePageController extends BaseController
{
    protected $template;

    public function __construct()
    {
        parent::__construct();
        $this->template = "$this->template.home";
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $club_name = $this->clubname;
        return view("$this->template.index", compact('club_name'));
    }

    public function outings()
    {
        return view("$this->template.outings");
    }

    public function facilities()
    {
        return view("$this->template.facilities");
    }
}

app/Http/Controllers/PreserveGolf/NewsController.php
<?php

namespace App\Http\Controllers\PreserveGolf;

use App\News;
use App\Http\Resources\News as NewsResource;

class NewsController extends BaseController
{
    /**
     * @return \Illuminate\Http\Resources\Json\AnonymousResourceCollection
     */
    public function index()
    {
        $news = News::with('picture')
            ->where('expired_at', '>', $this->nowDate())
            ->orWhere('expired_at', null)
            ->orderByDesc('created_at')
            ->paginate(2);
        return NewsResource::collection($news);
    }
}

app/Http/Controllers/PreserveGolf/RatesController.php
<?php

namespace App\Http\Controllers\PreserveGolf;

use Illuminate\Http\Request;

class RatesController extends BaseController
{
    protected $template;

    public function __construct()
    {
        parent::__construct();
        $this->template = "$this->template.rates";
    }

    public function index()
    {
        return view("$this->template.index");
    }

    public function annuals()
    {
        return view("$this->template.annuals");
    }

    public function playCards()
    {
        return view("$this->template.play-cards");
    }

    public function casualGolfer()
    {
        return view("$this->template.casual-golfer");
    }
}

app/Http/Controllers/PreserveGolf/TeeTimesController.php
<?php

namespace App\Http\Controllers\PreserveGolf;

class TeeTimesController extends BaseController
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return redirect('https://www.golf18network.com/arizona/tucson/the-preserve/golf/course/tee-times/7351.php?showall=1&display=embeddedWide');
    }
}

resources/views/master/preservegolf/home/facilities.blade.php
@extends('layouts.preservegolf')

@section('title', 'Facilities')

@section('content')
<div class="container">
    <div class="container">
        <!-- title -->
        <div class="page-title regular-spacing-section col-12">
            <h1>Facilities</h1>
        </div>
        <!-- /title -->
    </div>

    <!-- intro
    <section class="regular-spacing-section">
        <div class="container">
            <h2 class="section-head text-center">Who We Are</h2>
            <div class="lead col-10 col-sm-8 mx-auto">
                <p>Pastry tootsie roll jelly oat cake icing croissant tiramisu gingerbread donut. Croissant lemon drops halvah marshmallow apple pie tootsie roll. Jujubes bonbon candy candy canes macaroon fruitcake jelly-o danish. Dessert tart caramels cotton candy chocolate bar sugar plum. Pie jelly beans jelly carrot cake topping bonbon gummi bears. Cake carrot cake dessert. Oat cake muffin topping gummi bears sesame snaps toffee cheesecake sweet roll. Tiramisu cake gummi bears cake sweet roll brownie icing marshmallow. Pie chupa chups oat cake muffin tootsie roll liquorice muffin.</p>
            </div>
        </div>
    </section>
    -->

    <section class="regular-spacing-section">
        <div class="container">
            <div class="row flex-row-reverse align-items-center">
                <div class="col-lg-5 align-self-center text-center mb-3"><img src="{{ asset('images/Preserve-Golf-Shop.jpg') }}" alt="" class="img-fluid"></div>
                <div class="lead col-lg-7 text-left px-1 px-md-5">
                    <h2>Golf Shop</h2>
                    <p>Grab your logo apparel and the latest golf equipment while visiting our well-stocked Preserve Golf Shop. Featuring the best from Callaway, Cobra, Cleveland, Nike, Under Armour, and more. Golf Shop is open 7 AM to 5 PM daily.</p>
                </div>
            </div>
        </div>
    </section>
    <section class="regular-spacing-section">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-5 align-self-center text-center mb-3"><img src="{{ asset('images/Practice-Facilities.jpg') }}" alt="" class="img-fluid"></div>
                <div class="lead col-12 col-lg-7 text-left px-1 px-md-5">
                    <h2>Practice Facilities</h2>
                    <p>Preserve practice facilities feature a large putting green, short game practice area, and a practice tee. Our instructional programming covers all parts of the game. Individual, group, and playing lessons are available from our PGA Golf Professionals.</p>
                </div>
            </div>
        </div>
    </section>
    <section class="regular-spacing-section">
        <div class="container">
            <div class="row flex-row-reverse align-items-center">
                <div class="col-lg-5 align-self-center text-center mb-3"><img src="{{ asset('images/Preserve-Restaurant.jpg') }}" alt="" class="img-fluid"></div>
                <div class="lead col-lg-7 text-left px-1 px-md-5">
                    <h2>Preserve Restaurant & Bar</h2>
                    <p>Experience a taste of excellence at The Preserve after a challenging day on the links! A gem among restaurants with dining as spectacular as the views, The Preserve boasts a distinctive menu of Modern American Cuisine. Regular hours are 11 AM to 8 PM, Wednesday – Sunday. Closed Monday and Tuesday.</p>
                </div>
            </div>
        </div>
    </section>
    <div class="spacer"></div>
</div>
@endsection

resources/views/master/preservegolf/home/index.blade.php
@extends('layouts.preservegolf')

@section('title', 'SaddleBrooke')

@section('slider')
    <div id="carouselExampleIndicators" class="carousel slide lazy" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active text-center">
                <div class="carousel-caption text-center">
                    {{--<div class="display-3">
                        <strong>Lorem ipsum dolor</strong>
                    </div>
                    <p class="display-4">Save Up To 40% Off</p>--}}
                </div>
                <picture>
                    <source srcset="{{ asset("storage/images/slider/pr-slider-1-sm.jpg") }}" media="(max-width: 768px)">
                    <source srcset="{{ asset("storage/images/slider/pr-slider-1-md.jpg") }}" media="(max-width: 1124px)">
                    <source srcset="{{ asset("storage/images/slider/pr-slider-1-lg.jpg") }}">
                    <img src="{{ asset("storage/images/slider/pr-slider-1-lowres.jpg") }}" class="img-fluid" alt="First slide">
                </picture>
            </div>
            <div class="carousel-item text-center">
                <div class="carousel-caption text-center">
                    {{--<div>
                        <strong>Lorem ipsum dolor</strong>
                    </div>
                    <p>Premium brands</p>--}}
                </div>
                <picture>
                    <source srcset="{{ asset("storage/images/slider/pr-slider-2-sm.jpg") }}" media="(max-width: 768px)">
                    <source srcset="{{ asset("storage/images/slider/pr-slider-2-md.jpg") }}" media="(max-width: 1124px)">
                    <source srcset="{{ asset("storage/images/slider/pr-slider-2-lg.jpg") }}">
                    <img src="{{ asset("storage/images/slider/pr-slider-2-lowres.jpg") }}" class="img-fluid" alt="Second slide">
                </picture>
            </div>
            <div class="carousel-item text-center">
                <div class="carousel-caption text-center">
                    {{--<div>
                        <strong>Candy canes chocolate bar chocolate </strong>
                    </div>
                    <p>Icing tiramisu icing cake</p>--}}
                </div>
                <picture>
                    <source srcset="{{ asset("storage/images/slider/pr-slider-3-sm.jpg") }}" media="(max-width: 768px)">
                    <source srcset="{{ asset("storage/images/slider/pr-slider-3-md.jpg") }}" media="(max-width: 1124px)">
                    <source srcset="{{ asset("storage/images/slider/pr-slider-3-lg.jpg") }}">
                    <img src="{{ asset("storage/images/slider/pr-slider-3-lowres.jpg") }}" class="img-fluid" alt="Third slide">
                </picture>
            </div>
        </div>
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
@endsection

@section('content')
<!-- services -->
{{-- <section class="services py-2 regular-spacing-section bg-dark">
    <div class="container">
        <div class="row d-flex justify-content-around itext">
            <!-- service 1 -->
            <div class="d-flex service-item">
                <div class="d-none d-sm-block">
                    <svg class="icon">
                        <use xlink:href="images/assets/svg/symbols.svg#icon_tel"></use>
                    </svg>
                </div>
                <div>
                    <strong>Call Us {{ $phone }}</strong>
                </div>
            </div>
            <!-- /service  -->
            <!-- service 2 -->
            <div class="d-flex service-item">
                <div class="d-none d-sm-block">
                    <svg class="icon">
                        <use xlink:href="images/assets/svg/symbols.svg#icon_clock"></use>
                    </svg>
                </div>
                <div>
                    <strong>Hours 7AM - 5PM</strong>
                </div>
            </div>
            <!-- /service  -->
        </div>
    </div>
</section> --}}
<!-- /services -->
<!-- Welcome Section -->
<section class="top-cat regular-spacing-section">
    <div class="container">
        <h2 class="section-head text-center">Welcome to {{ $club_name }}</h2>
        <div class="row no-gutters">
            <!-- cat 1 -->
            <div class="col-12 col-sm-4 text-center">
                <div class="card text-white">
                    <a href="#"><img class="card-img clip img-fluid lazy" src="{{ asset("images/Preserve-Tee-Time.jpg") }}" alt="Clothing"></a>
                    <div class="card-img-overlay cat-overlay">
                        <h3 class="card-title text-center"><a href="{{ route('preserve.teetimes') }}" target="_blank"><small>Book</small><strong>Your Tee Time</strong></a></h3>
                    </div>
                </div>
            </div>
            <!-- /cat 1 -->
            <div class="col-12 col-sm-4 text-center">
                <div class="card text-white">
                    <a href="#"><img class="card-img clip img-fluid lazy" src="{{ asset("images/annual.jpg") }}" alt="Accesories"></a>
                    <div class="card-img-overlay cat-overlay">
                        <h3 class="card-title text-center"><a href="{{ route('preserve.rates.annuals') }}"><small>Annual</small><strong>Membership</strong></a></h3>
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-4 text-center">
                <div class="card text-white">
                    <a href="#"><img class="card-img clip img-fluid lazy" src="{{ asset("images/assets/categorie-banner-3.jpg") }}" alt="Card image"></a>
                    <div class="card-img-overlay cat-overlay">
                        <h3 class="card-title text-center"><a href="{{ route('preserve.outings') }}"><small>Group</small><strong>Events</strong></a></h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- /Welcome Section -->

<!-- NEWS Vue Component -->
<news-component></news-component>
<!-- NEWS Vue Component  -->


<!-- EVENTS Vue Component  -->
<events-component></events-component>
<!-- /EVENTS Vue Component  -->

<!-- TEXT CONTENT -->
<section class="regular-spacing-section bg-white">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2 class="section-head text-center" id="prod-desc">Golf On Top of the World</h2>
            </div>
            <div class="col-md-9 mx-auto lead text-center">
                <p>Winding through the beautiful canyons and foothills of the Santa Catalina Mountains, The Preserve Golf Club 18-hole Championship Course gives you the feeling that you’re literally on top of the world. The layout features rolling fairways and undulating greens, presenting an enjoyable challenge to novices as well as avid golfers. Boasting excellent views and dramatic elevation changes, The Preserve is a terrific choice for your regular rounds of golf, or as a new destination for you and friends when visiting Tucson.</p>
                <br>
            </div>
        </div>
    </div>
</section>
<!-- /TEXT CONTENT -->

<div class="regular-spacing-section banners">
    <div class="container">
        <br>
        <div class="row">
            <div class="col-sm-6 text-center">
                <div class="banner full-image">
                    <div class="banner-caption">
                        <h4>Facilities <small>Golf, Shop and Dine</small></h4>
                        <a href="{{ route('preserve.facilities') }}">Discover The Preserve</a>
                    </div>
                    <div class="banner-img">
                        <img src="{{ asset("images/home-page-preserve-facilities-image.jpg") }}" class="lazy" alt="Card image">
                    </div>
                </div>
            </div>
            <div class="col-sm-6 text-center">
                @include('partials.preserve-overview-table')
            </div>
        </div>
    </div>
</div>
@endsection